services:
  - type: web
    name: tradetracker
    env: python
    buildCommand: "bash build.sh"
    startCommand: "uv run gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true